config/routes.rb
CacheMap::Application.routes.draw do

  resources :geonames

  root :to => 'geonames#index'
  get 'results' => 'geonames#results'
  get 'map' => 'geonames#map'
  get 'poem' => 'geonames#poem'
  get 'hunt' => 'geonames#hunt'
  get 'clues' => 'geonames#clues'
  get 'facts' => 'geonames#facts'
  get 'book' => 'geonames#book'
  get 'forrestfenn' => 'geonames#fenn'
  get 'blogs' => 'geonames#blogs'

end

app/models/geoname.rb
class Geoname < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  attr_accessible :feature_id,
                  :feature_name,
                  :feature_class,
                  :state_alpha,
                  :state_numeric,
                  :county_name,
                  :county_numeric,
                  :primary_lat_dms,
                  :prim_long_dms,
                  :prim_lat_dec,
                  :prim_long_dec,
                  :source_lat_dms,
                  :source_long_dms,
                  :source_lat_dec,
                  :source_long_dec,
                  :elev_in_m,
                  :elev_in_ft,
                  :map_name,
                  :date_created,
                  :date_edited

  def self.search(params)
    tire.search per_page: 2000 do
      query do
        boolean do
          must { string params[:query] } if params[:query].present?
          must { string 'state_alpha:' + params[:select_state].keys.join(' OR state_alpha:') } if params[:select_state].present?
          must { range :elev_in_ft, {gte: params[:elevation_5000] ? 5000 : 0} }
        end
      end
    end
  end

  # to delete Elastic Search (seed) data for Geoname table,
  # run "curl -XDELETE 'http://localhost:9200/geonames/'" from terminal,
  # then run rake db:reset to repopulate database
end

  # def self.search(params)
  #   tire.search per_page: 15 do
  #     # query do
  #       # terms :feature_name, ['river', 'arkansas'], :minimum_match => 2
  #     # end
  #     # if params[:query] == ""
  #     #   redirect_to "/geonames"
  #     # else
  #       query { string params[:query] } if params[:query].present?
  #       filter :range, elev_in_ft: {gte: params[:elevation_5000] ? 5000 : 0}
  #       # filter :terms, state_alpha: ["CO", "ID"]
  #       # query { terms :state_alpha, ['CO'] }
  #       # filter :range, state_alpha: { params[:geoname] }
  #       # filter :range, elev_in_ft: {lt: 5000}
  #       # sort { by :feature_name }
  #       # if params[:query].blank?
  #     # end
  #   end
  # end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/geonames_controller.rb
class GeonamesController < ApplicationController

  def index
    @geonames = Geoname.search(params)
    # raise notice.inspect
  end

  def map
    @geo_search = Geoname.search(params)
    if params[:query] == ""
      redirect_to :back, :flash => { :notice => "Please enter clues to search for" }
    elsif @geo_search.count == 0
      redirect_to geonames_path, :flash => { :notice => "Sorry, no results for that search. Please enter a new search." }
    end
  end

  def show
    @geoname = Geoname.where(feature_id: params[:id]).first
    # @geoname = Geoname.find_by_feature_id(params[:id])
  end

  def poem

  end

  def hunt

  end

  def clues

  end

  def facts

  end

  def book

  end

  def fenn

  end

  def blogs

  end

  def gallery

  end

  def new
    @geoname = Geoname.new
  end

  def create
    @geoname = Geoname.find_all_by_feature_name(params[:feature_name])
    redirect_to results_path
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @geonames = Geoname.search(params)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end

  def search

  end

  def map
    # render :template => "map"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geonames_helper.rb
module GeonamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/geonames/_nav_bar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="/">CacheMap </a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <li class="active"><a href="/geonames">Home</a></li>
      <li class="divider"></li>
      <li><a href="#">Main Item 2</a></li>
      <li class="divider"></li>
      <li class="has-dropdown"><a href="#">Main Item 3</a>

        <ul class="dropdown">
          <li class="has-dropdown"><a href="#">Dropdown Level 1a</a>

            <ul class="dropdown">
              <li><label>Dropdown Level 2 Label</label></li>
              <li><a href="#">Dropdown Level 2a</a></li>
              <li><a href="#">Dropdown Level 2b</a></li>
              <li class="has-dropdown"><a href="#">Dropdown Level 2c</a>

                <ul class="dropdown">
                  <li><label>Dropdown Level 3 Label</label></li>
                  <li><a href="#">Dropdown Level 3a</a></li>
                  <li><a href="#">Dropdown Level 3b</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Dropdown Level 3c</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 2d</a></li>
              <li><a href="#">Dropdown Level 2e</a></li>
              <li><a href="#">Dropdown Level 2f</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Level 1b</a></li>
          <li><a href="#">Dropdown Level 1c</a></li>
          <li class="divider"></li>
          <li><a href="#">Dropdown Level 1d</a></li>
          <li><a href="#">Dropdown Level 1e</a></li>
          <li><a href="#">Dropdown Level 1f</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider hide-for-small"></li>
      <li class="has-dropdown"><a href="#">Main Item 4</a>

        <ul class="dropdown">
          <li><label>Dropdown Level 1 Label</label></li>
          <li class="has-dropdown"><a href="#" class="">Dropdown Level 1a</a>

            <ul class="dropdown">
              <li><a href="#">Dropdown Level 2a</a></li>
              <li><a href="#">Dropdown Level 2b</a></li>
              <li class="has-dropdown"><a href="#">Dropdown Level 2c</a>

                <ul class="dropdown">
                  <li><a href="#">Dropdown Level 3a</a></li>
                  <li><a href="#">Dropdown Level 3b</a></li>
                  <li><a href="#">Dropdown Level 3c</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 2d</a></li>
              <li><a href="#">Dropdown Level 2e</a></li>
              <li><a href="#">Dropdown Level 2f</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Level 1b</a></li>
          <li><a href="#">Dropdown Level 1c</a></li>
          <li class="divider"></li>
          <li><label>Dropdown Level 1 Label</label></li>
          <li><a href="#">Dropdown Level 1d</a></li>
          <li><a href="#">Dropdown Level 1e</a></li>
          <li><a href="#">Dropdown Level 1f</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
<!--       <li class="has-form">
        <form>
          <div class="row collapse">
            <div class="small-8 columns">
              <input type="text">
            </div>
            <div class="small-4 columns">
              <a href="#" class="alert button">Search</a>
            </div>
          </div>
        </form>
      </li> -->
      <li class="divider show-for-small"></li>
      <li class="has-form">
        <a class="button" href="#">Button!</a>
      </li>
    </ul>
  </section>
</nav>

app/views/geonames/blogs.html.erb
  <%= render :partial => "/side_bar" %>

app/views/geonames/book.html.erb
  <%= render :partial => "/side_bar" %>

app/views/geonames/clues.html.erb
  <%= render :partial => "/side_bar" %>

  <div class="large-1 columns"><div></div></div>
    <div class="large-8 columns">
      <div id="poem-panel">
        <div id="poem-style" class="poem-background"></div>
          <div class="row">
            <div class="large-12 columns">
              <div id="poem-title" style="color: black;">Clues</div>
                <div id="poem-body" style="color: black;">
                  <p></p>
                  Clue 1: The treasure is in the Rocky Mountains
                  <br><i>Source: The Thrill of the Chase (book)</i>
                  <br>
                  <br>Clue 2: The treasure is north of Sante Fe, New Mexico
                  <br><i>Source: The Thrill of the Chase (book)</i>
                  <br>
                  <br>Clue 2: The treasure is above 5000 feet.
                  <br><i>Source: The Today Show (airdate)</i>
                  <br>
                  <br>Clue 3: The treasure is not in a graveyard
                  <br><i>Source: The Today Show (airdate)</i>
                  <br>
                  <br>Clue 4: The treasure is not in Nevada
                  <br><i>Source: personal correspondence with FF</i>
                  <br>
                </div>

            </div>
          </div>

      </div>
    </div>

</div>

app/views/geonames/deleted_code.html.erb
        // var arkLatlng = new google.maps.LatLng(<%= @geo_search[1].prim_lat_dec %>, <%= @geo_search[1].prim_long_dec %>);
        // var newcenter = new google.maps.LatLngBounds(38.000, -104.000, 39.000, -103.000).getCenter();
        // var selectcenter = new google.maps.LatLng(37.000, -105.000);
        // var marker = new google.maps.Marker({
        //   position: arkLatlng,
        //   map: map,
        //   title: "<%= @geo_search[-1].feature_id %>"
        // });

        // var Item_1 = new google.maps.LatLng(37.00, -107.00);
        // var myPlace = new google.maps.LatLng(45.4555729, 9.169236);
        // var Item_2 = new google.maps.LatLng(30.00, -108.00);
        // var Item_3 = new google.maps.LatLng(32.00, -110.00);
        // var Item_4 = new google.maps.LatLng(39.00, -103.00);
        // var Item_5 = new google.maps.LatLng(37.00, -109.00);


        // var marker = new google.maps.Marker({
        //     position: Item_1,
        //     map: map
        // });
        // var marker = new google.maps.Marker({
        //     position: myPlace,
        //     map: map
        // });
        // var marker = new google.maps.Marker({
        //     position: Item_2,
        //     map: map
        // });
        // var marker = new google.maps.Marker({
        //     position: Item_3,
        //     map: map
        // });
        // var marker = new google.maps.Marker({
        //     position: Item_4,
        //     map: map
        // });
        // var marker = new google.maps.Marker({
        //     position: Item_5,
        //     map: map
        // });

app/views/geonames/facts.html.erb
  <%= render :partial => "/side_bar" %>

app/views/geonames/fenn.html.erb
  <%= render :partial => "/side_bar" %>

app/views/geonames/hunt.html.erb
  <%= render :partial => "/side_bar" %>

  <div class="large-9 columns">
    Body text
  </div>
</div>

app/views/geonames/index.html.erb
<div class="row">
  <div class="large-8 columns"></div>
  <div class="row">
    <div class="large-1 columns"></div>
    <div class="large-6 columns" style="padding-top: 200px;">
      <div style="margin-right: 50px; margin-bottom: 60px; font-size: 110px">CacheMap
        <div style="font-size: 38px; margin-top: 10px;"> Find Forrest Fenn's Treasure</div></div>

        <% if flash[:notice] %>
          <div class='flash' id='flash-format'><%= flash[:notice] %></div>
        <% end %>

        <%= form_tag map_path, method: :get do %>
        <div class="row">
          <div class="large-5 columns">
            <div id="search-title">Search for clues </div></div>
          <div id="search-example" class="large-7 columns"> (ex: "river", "treasure chest")</div></div>
          <br><%= text_field_tag :query, params[:query] %>
          <%= submit_tag "Find Clues", feature_name: nil, class: "button large" %>

          <br><a href="poem" class="hidden">Search Options</a>

          <div class="hidden">
          <a href="hide-search" class="show">Hide Options</a>
            <script>
              $( document ).ready(function() {
                $( "div.hidden" ).hide();
                $( "a.hidden" ).click(function( event ) {
                  $( ".hidden" ).toggle();
                  event.preventDefault();
                });
                $( "a.show" ).click(function( event ) {
                  $( ".hidden" ).toggle();
                  event.preventDefault();
                });
              });
            </script>

            <br>
            <br><input id="elevation_5000" type="checkbox" value="yes" name="elevation_5000"> Only search locations above 5000 ft.
            <br>
            <br>

            <div style="font-size: 24px;">Select the states to search:</div>
            <div class="row">
              <div class="large-4 columns">
                <br><input id="select_state" type="checkbox" value="CO" name="select_state[CO]" checked="yes">Colorado
                <br><input id="select_state" type="checkbox" value="ID" name="select_state[ID]" checked="yes">Idaho
              </div>
              <div class="large-4 columns">
                <br><input id="select_state" type="checkbox" value="MT" name="select_state[MT]" checked="yes">Montana
                <br><input id="select_state" type="checkbox" value="NM" name="select_state[NM]" checked="yes">New Mexico
              </div>
              <div class="large-4 columns">
                <br><input id="select_state" type="checkbox" value="UT" name="select_state[UT]" checked="yes">Utah
                <br><input id="select_state" type="checkbox" value="WY" name="select_state[WY]" checked="yes">Wyoming
              </div>
            </div>

        <% end %>
        </div>

    </div>

    <div class="large-5 columns">
      <div id="poem-panel">
        <div id="poem-style" class="poem-background"></div>
        <div class="row">
          <div class="12-large columns">
            <div class="hidden-poem">
              <div id="poem-title">The Thrill of the Chase</div>
              <div id="poem-body">
                <p></p>
                In 2010, an illustrious art dealer in Sante Fe, NM hid a chest of gold and jewels in the Rocky Mountains - a cache estimated to be worth over $1m. He wrote a poem containing nine clues that lead directly to his secret treasure spot.
                <p></p>
                CacheMap helps you decipher the poem by locating geographic places related to the clues. By finding the right landmarks, you could be the first to blaze a trail straight to the treasure!
                <p></p>
                <%= image_tag "treasure_chest_short.jpg" %>
              </div>
            </div>

            <script>
              $( document ).ready(function() {
                $( ".hidden-poem" ).hide();
                $( ".hidden-poem" ).slideDown( 3000 );
              });
            </script>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/geonames/map.html.erb
<% content_for :map do %>
  <%= render :partial => "/map_results" %>
<% end %>

<div class="row">
</div>

<div class="row">
  <div class="large-8 columns" style="padding: 30px;">
    <div id="map-canvas" style="height: 600px; border: 2px solid darkgreen; box-shadow: 0px 0px 8px;">
    </div>

    <div class="row">
        <br>
        <br>
          <% if flash[:notice] %>
            <div class='flash' id='flash-format'><%= flash[:notice] %></div>
          <% end %>
        <%= form_tag map_path, method: :get do %>
            <div id="search-title">New Search</div>
              <br><%= text_field_tag :query, params[:query] %>
                <input id="elevation_5000" type="checkbox" value="yes" name="elevation_5000"> Only search locations above 5000 ft.
              <%= submit_tag "Find Clues", feature_name: nil, class: "button large" %>

              <div style="font-size: 24px;">Select the states to search:</div>
                <div class="row">
                  <div class="large-4 columns">
                    <br><input id="select_state" type="checkbox" value="CO" name="select_state[CO]" checked="yes">Colorado
                    <br><input id="select_state" type="checkbox" value="ID" name="select_state[ID]" checked="yes">Idaho
                  </div>
                  <div class="large-4 columns">
                    <br><input id="select_state" type="checkbox" value="MT" name="select_state[MT]" checked="yes">Montana
                    <br><input id="select_state" type="checkbox" value="NM" name="select_state[NM]" checked="yes">New Mexico
                  </div>
                  <div class="large-4 columns">
                    <br><input id="select_state" type="checkbox" value="UT" name="select_state[UT]" checked="yes">Utah
                    <br><input id="select_state" type="checkbox" value="WY" name="select_state[WY]" checked="yes">Wyoming
                  </div>
                </div>

            <% end %>
    </div>
  </div>

  <div class="large-4 columns" style="padding: 30px;">
    <table style="border: 1px solid darkgreen; box-shadow: 0px 0px 7px;">
      <thead>
        <tr>
          <th width="300px;"><div style="font-size: 26px; margin-top: 10px;">Search Results</div><br>
          <div style="font-size: 18px; padding-bottom: 5px;"><%= @geo_search.count %> places with "<%= params["query"] %>"</div></th>
        </tr>
      </thead>
      <tbody>
      <% @geo_search.each do |geoname| %>
        <tr>
          <td>Name: <%= link_to geoname.feature_name, geoname_path(geoname.feature_id) %><br>

          Feature Type: <%= geoname.feature_class %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    </div>
  </div>
</div>

app/views/geonames/poem.html.erb
<div class="row">
  <div class="large-7 columns">
    <div class="large-1 columns"></div>
    <div class="large-10 columns">
      <div style="font-size: 60px; margin-top: 50px;">The Poem</div>
      <p><br><div style="font-size: 30px; ">Forrest Fenn wrote this poem and included it in his memoir, The Thrill of the Chase.
      He has says that it contains nine clues that if followed precisely, will lead to the end of his rainbow and the treasure.
      <br>
      <br>
      Forrest has also said that the poem contains all the clues necessary to find the treasure
      but that there are also "subtle hints" in the book.
      <br>
      <br>
      Find clues in the poem or the book and then search for them here to find places that they might refer to.</div>
    <% if flash[:notice] %>
            <div class='flash' id='flash-format'><%= flash[:notice] %></div>
          <% end %>
        <%= form_tag map_path, method: :get do %>
            <div id="search-title"></div>
              <br>
              <br>
              <br>
              <%= text_field_tag :query, params[:query] %>
                <input id="elevation_5000" type="checkbox" value="yes" name="elevation_5000"> Only search locations above 5000 ft.
              <%= submit_tag "Find Clues", feature_name: nil, class: "button large" %>

              <div style="font-size: 24px;">Select the states to search:</div>
                <div class="row">
                  <div class="large-4 columns">
                    <br><input id="select_state" type="checkbox" value="CO" name="select_state[CO]" checked="yes">Colorado
                    <br><input id="select_state" type="checkbox" value="ID" name="select_state[ID]" checked="yes">Idaho
                  </div>
                  <div class="large-4 columns">
                    <br><input id="select_state" type="checkbox" value="MT" name="select_state[MT]" checked="yes">Montana
                    <br><input id="select_state" type="checkbox" value="NM" name="select_state[NM]" checked="yes">New Mexico
                  </div>
                  <div class="large-4 columns">
                    <br><input id="select_state" type="checkbox" value="UT" name="select_state[UT]" checked="yes">Utah
                    <br><input id="select_state" type="checkbox" value="WY" name="select_state[WY]" checked="yes">Wyoming
                  </div>
                </div>

            <% end %>
          </div>
    <div class="large-1 columns"></div>

  </div>
    <div class="large-5 columns">
      <div id="poem-panel">
        <div id="poem-style" class="poem-background"></div>
          <div class="row">
            <div class="12-large columns">
              <div class="hidden-poem">
              <div id="poem-title">The Thrill of the Chase</div>
                <div id="poem-body">
                  <div style="text-align: center"><i>by Forrest Fenn</i></div>
                  <p></p>
                    As I have gone alone in there
                    <br>And with my treasures bold,
                    <br>I can keep my secret where,
                    <br>And hint of riches new and old.
                    <br>
                    <br>Begin it where warm waters halt
                    <br>And take it in the canyon down,
                    <br>Not far, but too far to walk.
                    <br>Put in below the home of Brown.
                    <br>
                    <br>From there it's no place for the meek,
                    <br>The end is ever drawing nigh;
                    <br>There'll be no paddle up your creek,
                    <br>Just heavy loads and water high.
                    <br>
                    <br>If you've been wise and found the blaze,
                    <br>Look quickly down, your quest to cease,
                    <br>But tarry scant with marvel gaze,
                    <br>Just take the chest and go in peace.
                    <br>
                    <br>So why is it that I must go
                    <br>And leave my trove for all to seek?
                    <br>The answer I already know,
                    <br>I've done it tired, and now I'm weak.
                    <br>
                    <br>So hear me all and listen good,
                    <br>Your effort will be worth the cold.
                    <br>If you are brave and in the wood
                    <br>I give you title to the gold.
                    <br>
                    <br>
                    <%= image_tag "treasure_chest_short.jpg" %>
                  </i>
                </div>

                <script>
                  $( document ).ready(function() {
                    $( "#poem-body" ).hide();
                    $( "#poem-body" ).slideDown( 3000 );
                  });
                </script>

              </div>
            </div>
          </div>

      </div>
    </div>
  </div>
</div>

app/views/geonames/results.html.erb
<h2>Search Results page</h2>

<h3>Search results:</h3>
  <% @geonames.each do |geoname| %>
    <ul>
      <li><h4>
      Name: <%= link_to geoname.feature_name, geoname_path(geoname.feature_id) %><br>
      Class: <%= geoname.feature_class %>
      <!-- <br><%= link_to 'map', :controller => 'geonames', :action => 'map', :id => @geoname %> -->
      </h4></li>
    </ul>
  <% end %>

<p><%= link_to "Index", geonames_path %>

<p><%= link_to "Map", map_path %>

app/views/geonames/show.html.erb
<% content_for :map do %>
  <%= render :partial => "/map_single" %>
<% end %>

<div class="row">
  <div class="large-8 columns" style="padding: 30px;">
    <div id="map-canvas" style="height: 600px; border: 2px solid darkgreen;
    box-shadow: 0px 0px 8px;">
    </div>
  </div>

  <div class="large-4 columns" style="padding: 30px;">
    <div class="row">
      <table style="border: 1px; box-shadow: 0px 0px 7px;">
        <thead>
          <tr>
            <th width="300px;"><div style="font-size: 26px; line-height: 1.1em"><%= @geoname.feature_name %></div>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr><td>Feature Type: <%= @geoname.feature_class %>
          <tr><td>State: <%= @geoname.state_alpha %></td></tr>
          <tr><td>County: <%= @geoname.county_name %></td></tr>
          <tr><td>Latitude: <%= @geoname.prim_lat_dec %></td></tr>
          <tr><td>Longitude: <%= @geoname.prim_long_dec %></td></tr>
          <tr><td>Elevation: <%= @geoname.elev_in_ft %> ft.</td></tr>

        </tbody>
      </table>
    </div>
    <div class="row">
      <p style="align: center;"><br><%= link_to "Back to Search Results", :back, class: "button" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica:400,400italic">
    <%= favicon_link_tag 'star_gold_256.png' %>

    <title><%= content_for?(:title) ? yield(:title) : "CacheMap" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tags %>

    <!-- shim for HTML5 elements for older browsers -->
    <%= javascript_include_tag "vendor/custom.modernizr.js" %>

    <%= yield :map %>

  </head>

  <body>

    <%= render :partial => "/nav_bar" %>

    <!-- to include all of Foundation Core and all JS plugins -->
    <%= javascript_include_tag "foundation/foundation.js" %>

    <div id="landing-container">
      <div id="map-background" class="translucent"></div>

    <%= yield %>

    </div>

  </body>

  <footer>
    <%= yield :scripts %>
  </footer>

</html>

app/views/search/index.html.erb
<% @geonames.each do |geoname| %>
  <h4>
    <%= link_to geoname.feature_name, geoname %>: <%= geoname.feature_class %>
  </h4>
<% end %>

app/views/welcome/home.html.erb
<b>Home</b> page view

<p><%= link_to "Search page", search_path %>

<p><%= link_to "Map page", map_path %>

app/views/welcome/map.html.erb
<b>Map</b> page view

<p><%= link_to "Home page", home_path %>

<p><%= link_to "Search page", search_path %>


<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map-canvas { height: 100% }
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAhaz5wjB5uu0vCAjTFLT8o5om2zk7UMYk&sensor=false">
    </script>
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(-34.397, 150.644),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>
  <body>
    <div id="map-canvas"/>
  </body>
</html>

app/views/welcome/search.html.erb
<b>Search</b> page view

<p><%= link_to "Home page", home_path %>

<p><%= link_to "Map page", map_path %>